name: CI/CD Workflow for .NET

on:
  push:
    branches:
      - main # Run workflow on pushes to the main branch
  pull_request:
    branches:
      - main # Run workflow on pull requests to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Change to ubuntu-22.04 or ubuntu-24.04 if testing compatibility

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0' # Specify the .NET version (e.g., 6.0, 7.0, 9.0, etc.)

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the project
      - name: Build the project
        run: dotnet build --no-restore --configuration Release

      # Step 5: Run tests and generate .trx results
      - name: Run tests
        run: dotnet test --no-build --configuration Release --logger "trx;LogFileName=test-results.trx"

      # Step 6: Upload Build Artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: '**/bin/Release/**/*' # Adjust path based on your project structure

      # Step 7: Upload Test Results
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/TestResults/*.trx' # Ensure this matches your test results location

     
