name: CI/CD Workflow for .NET

on:
  push:
    branches:
      - main # Run workflow on pushes to the main branch
  pull_request:
    branches:
      - main # Run workflow on pull requests to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0' # Specify the .NET version you want to use

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build the project
        run: dotnet build --no-restore --configuration Release

      # Run tests and generate .trx results
      - name: Run tests and generate results
        run: dotnet test --no-build --configuration Release --logger "trx;LogFileName=test-results.trx"

      # Upload Build Artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: '**/bin/Release/**/*' # Adjust path based on your build output structure

      # Upload Test Results
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/TestResults/*.trx' # Path to the generated .trx files

     
